name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: 1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_auth_platform_interface: ^7.1.4
  intl_phone_number_input: ^0.7.4
  pinput: ^4.0.0
  flutter_native_splash: ^2.3.10
  firebase_messaging: ^14.7.16
  grouped_list: ^5.1.2

dev_dependencies: 
  flutter_lints: ^3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/




